### ISSUE TITLE
As a user, I want to login so that I can see my profile

### ISSUE THREAD

**Issue by waiyan13** [techyangon/poly-ui#1]
## Acceptance Criteria

Feature: Authentication

    Scenario: the user wants to log in
        Given the user is not logged in
        When the user navigates to the website
        Then the website should redirect the user to login page

    Scenario: the user wants to log in
        Given the user has correct credentials
        When the user navigates to the website
        And enters incorrect credentials
        Then the website should prompt with error

    Scenario: the user wants to log in
        Given the user has correct credentials
        When the user navigates to the website
        And enters correct credentials
        Then the website should redirect me to home page

## Tasks List

- [x] Implement login form
- [x] Implement form validation
- [x] Implement authentication request
- [x] Refresh access token after expiry
- [x] Redirect to login after refresh token expiry

## Resources

- [MUI](https://mui.com)

**Comment by waiyan13** [comment]
Resolved by #12.
